FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/tools
RUN gcc bin2c.c -o bin2c

FROM ubuntu:22.04 as package
COPY --from=builder /repo/tools/bin2c /
