name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/psptoolchain:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base autoconf automake zlib-dev

    - name: Compile PSPSDK
      run: |
        ./bootstrap
        ./configure
        make clean
        make -j $(getconf _NPROCESSORS_ONLN)
        make install
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Compile Examples
      run: |
        cd src/samples && make -f Makefile.samples
    
    - name: Compress Samples folder folder
      run: |
        tar -zcvf samples.tar.gz src/samples
    
    - name: Upload Samples artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: samples-${{ steps.slug.outputs.sha8 }}
        path: samples.tar.gz
